function A = serine_ODE(in1,in2,in3)
%serine_ODE
%    A = serine_ODE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    11-Jul-2024 15:24:41

GLYg_1 = in1(1,:);
GLYg_2 = in1(2,:);
GLYg_3 = in1(3,:);
GLYg_4 = in1(4,:);
MTHFg_1 = in1(5,:);
MTHFg_2 = in1(6,:);
SERg_1 = in1(7,:);
SERg_2 = in1(8,:);
SERg_3 = in1(9,:);
SERg_4 = in1(10,:);
SERg_5 = in1(11,:);
SERg_6 = in1(12,:);
SERg_7 = in1(13,:);
SERg_8 = in1(14,:);
c1 = in3(1,:);
c2 = in3(2,:);
v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
v4 = in2(4,:);
v5 = in2(5,:);
t2 = 1.0./c1;
t3 = 1.0./c2;
t4 = v2-1.0;
t5 = 1.0./t4;
t6 = t5.*v2.*2.0e+2;
t7 = -t6;
A = [-t2.*(SERg_1+SERg_2).*(t6-v1)+GLYg_1.*t2.*t6-GLYg_1.*t2.*v3-GLYg_1.*t2.*v5;-t2.*(SERg_3+SERg_4).*(t6-v1)+GLYg_2.*t2.*t6-GLYg_2.*t2.*v3-GLYg_2.*t2.*v5;-t2.*(SERg_5+SERg_6).*(t6-v1)+GLYg_3.*t2.*t6-GLYg_3.*t2.*v3-GLYg_3.*t2.*v5;-t2.*(SERg_7+SERg_8).*(t6-v1)+GLYg_4.*t2.*t6-GLYg_4.*t2.*v3-GLYg_4.*t2.*v5;-t3.*(t6-v1).*(SERg_1+SERg_3+SERg_5+SERg_7)+t3.*v3.*(GLYg_1+GLYg_3)+MTHFg_1.*t3.*t6-MTHFg_1.*t3.*v4;-t3.*(t6-v1).*(SERg_2+SERg_4+SERg_6+SERg_8)+t3.*v3.*(GLYg_2+GLYg_4)+MTHFg_2.*t3.*t6-MTHFg_2.*t3.*v4];
